services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - 9091:9090
    volumes:
      - ./etc/prometheus_config.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

  grafana:
    image: "grafana/grafana"
    ports:
      - 3001:3000
    volumes:
      - ./etc/grafana_dashboard_config.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./etc/grafana_datasource_config.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./dashboards:/var/lib/grafana/dashboards

  blackbox-exporter:
    image: "prom/blackbox-exporter"
    ports:
      - 9115:9115
    volumes:
      - ./etc/blackbox_config.yml:/etc/blackbox_exporter/config.yml

volumes:
  prometheus-storage:
    name: prometheus-storage
    external: true
